import {
  Activity,
  Atom,
  Baby,
  Bone,
  Brain,
  Clipboard,
  Clock,
  Coffee,
  Droplets,
  Ear,
  Eye,
  Footprints,
  Gauge,
  Heart,
  HeartHandshake,
  HeartPulse,
  Microscope,
  Moon,
  Radiation,
  Scan,
  ScanLine,
  ScanSearch,
  ShieldCheck,
  Smile,
  Stethoscope,
  Syringe,
  TestTube,
  Video,
  Watch,
  Wind,
  Zap,
  type LucideIcon,
} from "lucide-react";

const MAP: Record<string, LucideIcon> = {
  activity: Activity,
  atom: Atom,
  baby: Baby,
  bone: Bone,
  brain: Brain,
  clipboard: Clipboard,
  clock: Clock,
  coffee: Coffee,
  droplets: Droplets,
  ear: Ear,
  eye: Eye,
  footprints: Footprints,
  gauge: Gauge,
  heart: Heart,
  "heart-handshake": HeartHandshake,
  "heart-pulse": HeartPulse,
  microscope: Microscope,
  moon: Moon,
  radiation: Radiation,
  scan: Scan,
  "scan-line": ScanLine,
  "scan-search": ScanSearch,
  "shield-check": ShieldCheck,
  smile: Smile,
  stethoscope: Stethoscope,
  syringe: Syringe,
  "test-tube": TestTube,
  video: Video,
  watch: Watch,
  wind: Wind,
  zap: Zap,
};

export default function StudyIcon({ name, className = "", size = 18 }: { name: string; className?: string; size?: number }) {
  const Icon = MAP[name] ?? Stethoscope;
  return <Icon size={size} strokeWidth={1.75} className={className} />;
}
